# [group] lets us group together hosts so we can target the head node and compute nodes separately
# This is useful because the head and compute nodes often need different packages, configs, etc.

[head]
head ansible_host=head

[compute]
c1 ansible_host=c1
c2 ansible_host=c2
c3 ansible_host=c3

[cluster:children]
head
compute

[all:vars]
# set the user that ansible uses during SSH
ansible_user=root 

# disable host key checking for convenience, you should NOT do this on real clusters
# read more about host key checking: https://www.ibm.com/docs/en/zos/2.5.0?topic=program-host-key-checking
ansible_ssh_common_args="-o StrictHostKeyChecking=no"